"""empty message

Revision ID: 00c1fd89a05f
Revises: f6c73a243f60
Create Date: 2018-09-12 14:05:15.176488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c1fd89a05f'
down_revision = 'f6c73a243f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mac_addr', table_name='reserved_ipv4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('mac_addr', 'reserved_ipv4', ['mac_addr'], unique=True)
    # ### end Alembic commands ###
