"""empty message

Revision ID: 29b9860f60f1
Revises: 00c1fd89a05f
Create Date: 2018-09-12 14:35:56.209998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29b9860f60f1'
down_revision = '00c1fd89a05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('net_ipv4', sa.Column('vlan_num', sa.VARCHAR(length=150), nullable=True))
    op.drop_column('net_ipv4', 'opt_242')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('net_ipv4', sa.Column('opt_242', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('net_ipv4', 'vlan_num')
    # ### end Alembic commands ###
