"""empty message

Revision ID: 419ed7482581
Revises: b7425e9d553f
Create Date: 2018-05-31 14:26:29.854369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '419ed7482581'
down_revision = 'b7425e9d553f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mac_addr', table_name='hosts_allow')
    op.drop_table('hosts_allow')
    op.drop_table('net_ipv4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_ipv4',
    sa.Column('id', mysql.SMALLINT(display_width=6), nullable=False),
    sa.Column('interface', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('subnet_ipv4', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('netmask', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('default_gw', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('broadcast', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ip_range_start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ip_range_end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('failover_peer', mysql.VARCHAR(length=20), server_default=sa.text("'nr-dhcpd-failover'"), nullable=False),
    sa.Column('opt_242', mysql.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('hosts_allow',
    sa.Column('id', mysql.SMALLINT(display_width=6), nullable=False),
    sa.Column('hostname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('mac_addr', mysql.VARCHAR(length=18), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('mac_addr', 'hosts_allow', ['mac_addr'], unique=True)
    # ### end Alembic commands ###
