"""empty message

Revision ID: ec6055fb506b
Revises: 1dc1fcd7ce11
Create Date: 2018-09-12 10:51:20.562369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec6055fb506b'
down_revision = '1dc1fcd7ce11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('net_ipv4', sa.Column('vlan_num', sa.VARCHAR(length=150), nullable=True))
    op.drop_column('net_ipv4', 'opt_242')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('net_ipv4', sa.Column('opt_242', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('net_ipv4', 'vlan_num')
    # ### end Alembic commands ###
